### PR TITLE
bugfix of file filter

### PR DESCRIPTION
**Pull request by MartinHahner**

### CODE REVIEW

**Comment by MartinHahner** [comment]
it took 76h on my machine in the end to extract all training point clouds and save them as individual .ply files

**Comment by gdlg** [comment]
Thanks for the PR. If you are making extensive use of the point cloud, it might be worth for you to look at this [line](
https://github.com/gdlg/simple-waymo-open-dataset-reader/blob/b6dc17c9ea342f9e8c155c6b08fb98b64bcfe1fc/simple_waymo_open_dataset_reader/utils.py#L306) in utils.py. For some reason, the bottom of the range_image_pose seems to be all zeros for the top lidar. As I didn’t need to be very precise, I just ignored the problem and commented out those lines. However if you want to be accurate, it would be better to take into account the per-pixel pose given by the range_image_pose.

**Comment by MartinHahner** [comment]
image

the point clouds look fine to me, or what is the issue exactly? 
I think I don't understand what should be stored in the pixel_pose and what it is used for.

**Comment by gdlg** [comment]
The range_image_pose is used to take into account that if the ego-vehicle is moving, each point  would have been taken from at a slightly different time with a slightly different pose due to the LIDAR spinning. The range_image_pose give you the exact pose (in world space) of each point in the LIDAR range image at the time that it was captured.

So you might not see much difference if the vehicle is moving slowly but the effect should be much more noticeable at higher speed. I haven’t really looked at it in details so I don’t know how significant it is.

**Pull request merged**
