### PR TITLE
correcting BGR to RGB in 'visualize_labels_and_lidar.py' example

### PR DESCRIPTION
**Pull request by MartinHahner**

### CODE REVIEW

**Comment by MartinHahner** [comment]
"TODO"s need to be replaced in 'extract_merged_pointclouds.py'

**Comment by gdlg** [comment]
Hi Martin,

Thanks for the contribution. I was wondering if you could add a small description and use the command line parameters instead of TODOs for `path` and `save_path_root`.

Something as simple as what is currently in `examples/visualise_labels_and_lidar.py` would be enough:
```
if len(sys.argv) != 2:
    print("""Usage: python display_laser_on_image.py <datafile>
Display the groundtruth 3D bounding boxes and LIDAR points on the front camera video stream.""")
    sys.exit(0)

# Open a .tfrecord
filename = sys.argv[1]
```

**Comment by MartinHahner** [comment]
Hi Grégoire, 
I was hoping you would fix it the way you like. 
But in that case, I will try to fix it myself tomorrow.

Greets, Martin

**Comment by gdlg** [comment]
Yes, I can fix the parameters easily if you prefer but it would be nice to have a brief description of what the example does.

Thanks, Greg.

**Comment by MartinHahner** [comment]
I added a short description and added the parameter support from the command line

**Comment by gdlg** [comment]
Perfect, thank you very much. It’s good to know that the whole process can take 3 days :-)

**Pull request merged**
